In [15]:
import torch
from torch.autograd import grad
import torch.nn.functional as F

In [16]:
x = torch.tensor([3.])
w = torch.tensor([2.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
a = F.relu(x*w+b)

In [17]:
a

tensor([7.], grad_fn=<ReluBackward0>)

In [18]:
grad(a, w, retain_graph = True)

(tensor([3.]),)

In [19]:
grad(a, b)

(tensor([1.]),)

In [23]:
x = torch.tensor([-1.])
w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)

def my_relu(z):
    if z > 0:
        return z
    else:
        z[:] = 0
        return z

a = my_relu(x*w + b)
grad(a, w, retain_graph = False)

(tensor([-0.]),)