In [2]:
import torch

In [3]:
a = torch.tensor([1., 2., 3.,])

print(a.dtype)

torch.float32


In [4]:
print(a.shape)

torch.Size([3])


In [5]:
print(a.dot(a))

tensor(14.)


In [6]:
print(torch.cuda.is_available())

False


/home/unique/anaconda3/envs/dl/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [7]:
b = torch.tensor([7.,8.,9.])

In [8]:
b+1 # Broadcasting

tensor([ 8.,  9., 10.])

In [13]:
X = torch.arange(6).view(2,3)
X

tensor([[0, 1, 2],
        [3, 4, 5]])

In [15]:
w = torch.tensor([1,2,3])
w

tensor([1, 2, 3])

In [16]:
X.matmul(w)

tensor([ 8, 26])

In [17]:
w = w.view(-1,1)

In [18]:
X.matmul(w)

tensor([[ 8],
        [26]])

In [20]:
# Broadcasting vector to X
X + torch.tensor([1,2,3])

tensor([[1, 3, 5],
        [4, 6, 8]])